name: master_test

on:
  push:
    branches: [ master ]

jobs:
  master_test:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Find first scheme of default project
        run: |
          echo "SCHEME=$(xcodebuild -list -json | jq -r '.project.schemes[0]')" >> $GITHUB_ENV

      - name: Build and test app
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          xcodebuild -scheme "$SCHEME" test CODE_SIGN_IDENTITY=- | xcpretty
